inherits = "base.toml"



[pacman]
    [pacman.packages]
    display_manager = ["lightdm",]
    cli_editor = ["nano", "gvim"]
    aur_manager = [
    ]
    shell_tools_extra = [
        "cronie",
	"virtualbox-guest-utils",
    ]
    base_customizations = [
        "gtk-engine-murrine",
    ]
    browser = [
        # "apricity-chrome-profile",
        "google-chrome",
        # "flashplugin",
    ]
    file_manager = [
        "nautilus",
        "gvfs-smb",
        "gvfs-mtp",
        "gvfs-google",
    ]
    system_apps = [
        "eog",
        "system-config-printer",
        "sushi",
    ]
    desktop_apps = [
        "filezilla",
        "gimp",
        "rhythmbox",
        "ice-ssb",
        "inkscape",
        "playonlinux",
        "steam",
        "syncthing-gtk",
        "totem",
        "transmission-cli",
        "transmission-gtk",
        "gufw",
        "wine",
    ]
    bluetooth = [
        "bluez-utils",
        "pulseaudio-bluetooth",
        "bluez",
        "bluez-libs",
        "bluez-utils",
        "bluez-firmware",
    ]
    system_tools = [
        "baobab",
    ]
    shell = ["zsh"]
    accessibility = ["orca"]
    
[zsh]
    [zsh.zshrc]
    base = [
        """source /usr/share/zsh/site-contrib/powerline.zsh""",
        """zstyle ':completion:*' menu select""",
    ]


[systemd]
    [systemd.services]
    bluetooth = [
        "bluetooth",
    ]
    gdm = [
        "gdm-plymouth",
    ]


