inherits = "base.toml"



[pacman]
    [pacman.packages]
    display_manager = ["sddm"]
    cli_editor = ["nano", "gvim"]
    aur_manager = [
        "pacaur",
        "yaourt-git",
	"pamac-tray-appindicator",
    ]
    shell_tools_extra = [
        "cronie",
        "gksu",
        "xdg-user-dirs-gtk",
        "python2-powerline-git",
	"virtualbox-guest-utils",
    ]
    base_customizations = [
        "gtk-engine-murrine",
    ]
    browser = [
        # "apricity-chrome-profile",
        "google-chrome",
        "google-talkplugin",
        "icedtea-web",
        # "flashplugin",
    ]
    file_manager = [
        "nautilus",
        "gvfs-smb",
        "gvfs-mtp",
        "gvfs-google",
    ]
    system_apps = [
      
        "eog",
        "evince",
        "gedit",
        "pamac-aur",
        "system-config-printer",
        "sushi",
    ]
    desktop_apps = [
        "filezilla",
        "gimp",
        "rhythmbox",
        "ice-ssb",
        "inkscape",
        "libreoffice-still",
        "playonlinux",
        "steam",
        "syncthing-gtk",
        "totem",
        "transmission-cli",
        "transmission-gtk",
        "gufw",
        "wine",
    ]
    bluetooth = [
        "bluez-utils",
        "pulseaudio-bluetooth",
        "bluez",
        "bluez-libs",
        "bluez-utils",
        "bluez-firmware",
    ]
    system_tools = [
        "baobab",
    ]
    shell = ["zsh"]
    accessibility = ["orca"]
    multimedia_lib = [
        "grilo-plugins",
        "faac",
        "faad2",
        "flac",
        "gsfonts",
        "gst-libav",
        "gst-plugin-libde265",
        "libdvdcss",
        "libdvdnav",
        "libdvdread",
        "libmatroska",
    ]
[zsh]
    [zsh.zshrc]
    base = [
        """source /usr/share/zsh/site-contrib/powerline.zsh""",
        """zstyle ':completion:*' menu select""",
    ]


[systemd]
    [systemd.services]
    bluetooth = [
        "bluetooth",
    ]
    sddm = [
        "sddm-plymouth",
    ]

[vim]
plugin_manager = "pathogen"
[vim.plugins]
    apricity = [
        "https://github.com/chriskempson/base16-vim.git/",
        "https://github.com/scrooloose/syntastic.git/",
        "https://github.com/bling/vim-airline/",
        "https://github.com/hynek/vim-python-pep8-indent.git/",
        "https://github.com/mhinz/vim-signify/",
        "https://github.com/flazz/vim-colorschemes.git",
        "https://github.com/luochen1990/rainbow.git",
        "https://github.com/rust-lang/rust.vim.git",
        "https://github.com/cespare/vim-toml.git",
    ]
[vim.vimrc]
    base = [
        "syntax on",
        "set autoread",
        "set number",
    ]
    python = [
        "set expandtab",
        "set shiftwidth=4",
        "set softtabstop=4",
    ]
    colorscheme = [
        "colorscheme kalisi",
        "set background=dark",
        "let t_Co = 256",
    ]
    airline = [
        "let g:airline_powerline_fonts = 1",
        "let g:syntastic_check_on_open = 1",
        "let g:airline#extensions#tabline#enabled = 1",
        "let g:airline_theme=\"base16\" ",
    ]
    # tfbrain = [
    #     'map <C-p> :w \| !./push.sh<CR><CR>',
    # ]
    ycm = [
        "let g:ycm_collect_identifiers_from_tags_files = 1",
        "let g:ycm_use_ultisnips_completer = 1",
        "let g:ycm_seed_identifiers_with_syntax = 1 ",
        "let g:ycm_complete_in_comments = 1",
        "let g:ycm_complete_in_strings = 1",
        "let g:ycm_autoclose_preview_window_after_insertion = 1",
        "let g:ycm_key_invoke_completion = '<S-Enter>'",
        "map <C-m> :YcmCompleter GoTo<CR>",
        "nmap <C-k> :YcmCompleter GetDoc<CR>",
    ]
    rainbow = [
        "let g:rainbow_active = 1"
    ]
