inherits = "desktop.toml"

[pacman]
    [pacman.packages]
    desktop_environment = [
        # 'gnome',
        'plasma-workspace',
        'plasma-workspace-wallpapers',
        'plasma-pa',
        'sddm-kcm',
        'breeze',
        'bluedevil',
    ]
    customizations = [
	'breeze-icons',

    ]

gtk_theme = "Flat-Plat"
icon_theme = "breeze"
wallpaper = "file:///usr/share/backgrounds/condres/condres_tux_purple.png"

