inherits = "desktop.toml"

[pacman]
    [pacman.packages]
    desktop_environment = [
        # 'gnome',
        'network-manager-applet',
    ]
    customizations = [
        'super-flat-remix-icon-theme',
	'flatplat-theme-git',
    ]


   
