inherits = "desktop.toml"

[pacman]
    [pacman.packages]
    desktop_environment = [
        # 'gnome',
        'network-manager-applet',
    ]
    customizations = [
        'super-flat-remix-icon-theme',
	'flatplat-theme-git',
    ]

[gnome]
gtk_theme = "Materia-compact"
icon_theme = "Flat-Remix"
wallpaper = "file:///usr/share/backgrounds/condres/condres_tux.png"
gtk_button_layout = ":minimize,maximize,close"
dynamic_workspaces = false
desktop_icons = true
   
