inherits = "desktop.toml"

[pacman]
    [pacman.packages]
    desktop_environment = [
        # 'gnome',
        'pantheon-git-meta',
    ]
    customizations = [
    ]

[gnome]
gtk_theme = "Artic Condres"
shell_theme = "Artic Condres"
icon_theme = "Numix Circle"
wallpaper = "file:///usr/share/backgrounds/condres/tahoe.jpg"
lock_background = "file:///usr/share/backgrounds/condres/tahoe.jpg"
gtk_button_layout = ":minimize,maximize,close"
dynamic_workspaces = false
desktop_icons = true
    [gnome.nautilus]
    default_zoom = 'small'
    [gnome.extensions]
    extensions = [
        "user-theme@gnome-shell-extensions.gcampax.github.com",
        "alwayszoomworkspaces@jamie.thenicols.net",
        "mediaplayer@patapon.info",
        "caffeine@patapon.info",
        "scroll-workspaces@gfxmonk.net",
        "dash-to-dock@micxgx.gmail.com",
        "suspend-button@laserb",
        "topIcons@adel.gadllah@gmail.com",
        "places-menu@gnome-shell-extensions.gcampax.github.com",
        "drive-menu@gnome-shell-extensions.gcampax.github.com",
        "remove-dropdown-arrows@mpdeimos.com",
        "Move_Clock@rmy.pobox.com"
    ]
    [gnome.favorite_apps]
    apps = [
        'google-chrome.desktop',
        'ice.desktop',
        'org.gnome.Nautilus.desktop',
        'empathy.desktop',
        'gnome-music.desktop',
        'org.gnome.Photos.desktop',
        'org.gnome.Totem.desktop',
        'libreoffice-writer.desktop',
        'libreoffice-impress.desktop',
        'libreoffice-calc.desktop',
        'org.gnome.gedit.desktop',
        'gnome-terminal.desktop',
        'gnome-tweak-tool.desktop',
        'gnome-control-center.desktop',
        'pamac-manager.desktop',
    ]

