[pacman]
keyrings = ["archlinux"]
    [pacman.packages]
    base = [
        "base",
        "base-devel",
        "linux-firmware",
    ]
    bootloader = [
        "grub",
        "os-prober",
    ]
    cli_editor = ["nano", "vim"]
    shell_tools = [
        "bash-completion",
        "xz",
        "bind-tools",
        "crda",
        "dosfstools",
        "efitools",
        "fakeroot",
        "fuse-exfat",
        "gvfs-afc",
        "jre8-openjdk",
        "gucharmap",
        "gzip",
        "haveged",
        "hunspell",
        "mc",
        "mtools",
        "openssh",
        "pkgfile",
        "python-lxml",
        "python-mako",
        "python-mock",
        "boost",
        "boost-libs",
        "refind-efi",
        "rfkill",
        "sudo",
        "smartmontools",
        "tar",
        "unrar",
        "unzip",
        "wget",
        "icu",
    ]
    # installer = [
    #     "calamares"
    # ]
    luks = [
        "mkinitcpio-openswap",
    ]
    fonts = [
        "ttf-arphic-uming",
        "ttf-baekmuk",
        "ttf-bitstream-vera",
        "ttf-dejavu",
        "ttf-droid",
        "ttf-freefont",
        "ttf-liberation",
    ]
    net = [
        "wireless_tools",
        "wpa_actiond",
        "whois",
        "tlp",
        "libmtp",
        "broadcom-wl-dkms",
        "ipw2100-fw",
        "ipw2200-fw",
        "zd1211-firmware",
        "modemmanager",
        "net-tools",
        "networkmanager-openvpn",
        "networkmanager-pptp",
        "ntfs-3g",
        "ntp",
        "samba",
    ]
    print_drivers = [
        "cups",
        "cups-pk-helper",
        "libcups",
        "hplip",
        "splix",
    ]
    audio_drivers = [
        "alsa-utils",
        "lib32-alsa-plugins",
        "pulseaudio-alsa",
    ]
    input_drivers = [
        "usbmuxd",
        "usb_modeswitch",
        "libinput",
        "xf86-input-libinput",
    ]
    xorg = [
        "xorg-fonts",
        "xorg-server",
        "xorg-server-utils",
        "xorg-xinit",
        "xorg-xkill",
        # "xorg-apps",
    ]
    video_drivers = [
        "mesa-libgl",
        "mesa",
        "lib32-mesa-libgl",
        "mesa-vdpau",
        "x264",
    ]


[systemd]
    [systemd.services]
    print = [
        "org.cups.cupsd",
    ]
    net = [
        "NetworkManager",
        "ModemManager",
        # "smbd",
        # "nmbd",
	"ntpd",
        "avahi-daemon"
    ]
    base = [
        "graphical.target",
        "systemd-rfkill"
    ]
    # pacman = [
    #     "pacman-init",
    # ]
