inherits = "base.toml"



[pacman]
    [pacman.packages]
    cli_editor = ["nano", "gvim"]
    aur_manager = [
    ]
    shell_tools_extra = [
        "cronie",
	"virtualbox-guest-utils",
    ]
    base_customizations = [
        "gtk-engine-murrine",
    ]
    browser = [
        # "apricity-chrome-profile",
        "google-chrome",
        # "flashplugin",
    ]
    file_manager = [
        "nautilus",
        "gvfs-smb",
        "gvfs-mtp",
        "gvfs-google",
    ]
    system_apps = [
        "eog",
        "system-config-printer",
        "sushi",
    ]
    bluetooth = [
        "bluez-utils",
        "pulseaudio-bluetooth",
        "bluez",
        "bluez-libs",
        "bluez-utils",
        "bluez-firmware",
    ]
    system_tools = [
        "baobab",
    ]
    shell = ["zsh"]
    accessibility = ["orca"]
    
[zsh]
    [zsh.zshrc]
    base = [
        """source /usr/share/zsh/site-contrib/powerline.zsh""",
        """zstyle ':completion:*' menu select""",
    ]


[systemd]
    [systemd.services]
    bluetooth = [
        "bluetooth",
    ]
    


